import { DocSection, Code } from './DocSection'

export function TypeScriptSection(): Node {
  return (
    <DocSection id="typescript" title="TypeScript">
      <p class="text-muted mb-3 text-[0.95rem]">Streem is built TypeScript-first. This guide covers the type patterns that matter most when building with Streem: signal generics, JSX configuration, CSSProperties, conditional classes, and component prop types.</p>

      <h3 class="text-[1.1rem] font-semibold text-text mt-8 mb-2">Signal typing</h3>
      <p class="text-muted mb-3 text-[0.95rem]">TypeScript infers the signal type from the initial value. Use explicit generics when the type cannot be inferred, such as union types or interfaces.</p>
      <Code>{`import { signal, computed, effect } from 'streeem'\nimport type { Signal } from 'streeem'\n\n// Type inferred from initial value\nconst count = signal(0)           // Signal<number>\nconst name = signal('')           // Signal<string>\nconst active = signal(false)      // Signal<boolean>\n\n// Explicit generic — required for union types and interfaces\ninterface User { id: number; name: string }\nconst user = signal<User | null>(null)   // Signal<User | null>\nconst status = signal<'idle' | 'loading' | 'done'>('idle')\n\n// computed() returns () => T (a getter function, NOT a Signal)\nconst doubled = computed(() => count() * 2)  // () => number\nconst label = computed(() => \`Count: \${count()}\`)  // () => string\n\n// Read computed in JSX as a function — called reactively by the renderer\nfunction Counter() {\n  const count = signal<number>(0)\n  const doubled = computed(() => count() * 2)\n\n  effect(() => {\n    // In effects and event handlers, call as a function\n    console.log('doubled:', doubled())\n  })\n\n  return (\n    <div>\n      {/* In JSX, pass the signal directly — renderer calls .value */}\n      <p>Count: {count}</p>\n      {/* Pass computed directly — renderer calls it as () => T */}\n      <p>Doubled: {doubled}</p>\n      <button on:click={() => count.set(count() + 1)}>+1</button>\n    </div>\n  )\n}`}</Code>

      <h3 class="text-[1.1rem] font-semibold text-text mt-8 mb-2">JSX configuration</h3>
      <p class="text-muted mb-3 text-[0.95rem]">Add these two fields to <code>compilerOptions</code> in your <code>tsconfig.json</code> to enable Streem's JSX factory and full type checking for intrinsic elements:</p>
      <Code>{`{\n  "compilerOptions": {\n    "jsx": "react-jsx",\n    "jsxImportSource": "streeem"\n  }\n}`}</Code>
      <p class="text-muted mb-3 text-[0.95rem]"><code>jsxImportSource: "streeem"</code> tells TypeScript to resolve JSX types from <code>streem/jsx-runtime</code>. This enables:</p>
      <Code>{`// Type-checked intrinsic elements (div, button, input, etc.)\n<div class="container" />         // 'class', not 'className'\n<button on:click={handler} />     // on:click is typed correctly\n<input type="text" value={val} />\n\n// Component functions return Node, not JSX.Element\nfunction MyComponent(): Node {\n  return <div>Hello</div>\n}\n\n// Render to DOM\nimport { render } from 'streeem'\nrender(MyComponent, document.getElementById('app')!)`}</Code>
      <p class="text-muted mb-3 text-[0.95rem]">Note: Streem uses <code>class</code> (not <code>className</code>) and event handlers are prefixed with <code>on:</code>. Both are enforced at the type level.</p>

      <h3 class="text-[1.1rem] font-semibold text-text mt-8 mb-2">CSSProperties</h3>
      <p class="text-muted mb-3 text-[0.95rem]">Import <code>CSSProperties</code> from <code>streem</code> to type extracted style objects. The <code>style</code> prop accepts either a static <code>CSSProperties</code> object or a reactive accessor <code>() =&gt; CSSProperties</code>.</p>
      <Code>{`import type { CSSProperties } from 'streeem'\n\n// Static style object — evaluated once\nconst gridStyle: CSSProperties = {\n  display: 'grid',\n  gridTemplateColumns: 'repeat(3, 1fr)',\n  gap: '16px',\n}\n\n// Use static object or inline object interchangeably\n<div style={gridStyle} />\n<div style={{ display: 'flex', alignItems: 'center', gap: '8px' }} />`}</Code>
      <Code>{`import { signal } from 'streeem'\nimport type { CSSProperties } from 'streeem'\n\nconst isDark = signal(false)\n\n// Reactive style — accessor re-runs when signal changes\nfunction ThemedCard() {\n  return (\n    <div style={() => ({\n      background: isDark() ? '#1a1a1a' : 'white',\n      color: isDark() ? '#f5f5f5' : '#111',\n      padding: '20px',\n      borderRadius: '8px',\n    } satisfies CSSProperties)}>\n      <button on:click={() => isDark.set(!isDark())}>Toggle theme</button>\n    </div>\n  )\n}`}</Code>

      <h3 class="text-[1.1rem] font-semibold text-text mt-8 mb-2">Conditional classes</h3>
      <p class="text-muted mb-3 text-[0.95rem]">Streem has no built-in <code>clsx</code> or <code>classnames</code>. Use template literals for simple cases and array filter for multiple conditions. Wrap in an accessor for reactive class switching.</p>
      <Code>{`import styles from './Button.module.css'\nimport { signal } from 'streeem'\n\nconst isActive = signal(false)\nconst isDisabled = signal(false)\n\n// Template literal — simple single condition\n<div class={\`\${styles.root} \${isActive() ? styles.active : ''}\`} />\n\n// Array filter — multiple conditions\nconst cls = [styles.root, isActive() && styles.active, isDisabled() && styles.disabled]\n  .filter(Boolean)\n  .join(' ')\n<div class={cls} />\n\n// Reactive — re-evaluates when signals change\n<div class={() => [\n  styles.root,\n  isActive() && styles.active,\n  isDisabled() && styles.disabled,\n].filter(Boolean).join(' ')} />`}</Code>
      <p class="text-muted mb-3 text-[0.95rem]">The reactive accessor form (<code>{'class={() => ...}'}</code>) is important when the class depends on signals — the renderer re-evaluates the accessor on signal change and patches the DOM attribute.</p>

      <h3 class="text-[1.1rem] font-semibold text-text mt-8 mb-2">Component prop types</h3>
      <p class="text-muted mb-3 text-[0.95rem]">Define a <code>Props</code> interface for each component. Use <code>unknown</code> for <code>children</code> — Streem children can be <code>Node</code>, <code>Node[]</code>, <code>string</code>, <code>Signal&lt;T&gt;</code>, or <code>() =&gt; T</code>. Cast to <code>Node</code> at the call site.</p>
      <Code>{`import type { Signal } from 'streeem'\n\ninterface CardProps {\n  title: string\n  subtitle?: string\n  variant?: 'default' | 'featured'\n  onClick?: () => void\n  children?: unknown   // unknown, not ReactNode\n}\n\nfunction Card(props: CardProps): Node {\n  return (\n    <div\n      class={\`card \${props.variant === 'featured' ? 'card--featured' : ''}\`}\n      on:click={props.onClick}\n    >\n      <h2>{props.title}</h2>\n      {props.subtitle && <p>{props.subtitle}</p>}\n      {props.children as Node}\n    </div>\n  ) as unknown as Node\n}\n\n// Reactive props — wrap in a signal when the value changes over time\ninterface StatusBadgeProps {\n  status: Signal<'idle' | 'loading' | 'done' | 'error'>\n}\n\nfunction StatusBadge(props: StatusBadgeProps): Node {\n  return (\n    <span class={() => \`badge badge--\${props.status()}\`}>\n      {props.status}\n    </span>\n  ) as unknown as Node\n}`}</Code>
      <p class="text-muted mb-3 text-[0.95rem]">Note: <code>children</code> is typed as <code>unknown</code> because Streem's JSX children are structurally flexible. Casting to <code>Node</code> when rendering is intentional and safe — the renderer handles all child types at runtime.</p>
    </DocSection>
  ) as unknown as Node
}
